package org.example.escuela;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-29T15:39:13.575+01:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://www.example.org/escuela/", name = "escuela")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Escuela {

    @WebMethod(operationName = "AsignaturaAlumno", action = "http://www.example.org/escuela/escuelaasignatura")
    @WebResult(name = "asignaturaResponse", targetNamespace = "http://www.example.org/escuela/", partName = "parameters")
    public AsignaturaResponse asignaturaAlumno(

        @WebParam(partName = "parameters", name = "asignaturaRequest", targetNamespace = "http://www.example.org/escuela/")
        AsignaturaRequest parameters
    );

    @WebMethod(operationName = "EvaluacionEscuela", action = "http://www.example.org/esceula/escuelaevaluacion")
    @WebResult(name = "evaluacionResponse", targetNamespace = "http://www.example.org/escuela/", partName = "parameters")
    public EvaluacionResponse evaluacionEscuela(

        @WebParam(partName = "parameters", name = "evaluacionRequest", targetNamespace = "http://www.example.org/escuela/")
        EvaluacionRequest parameters
    );

    @WebMethod(operationName = "EscuelaAlumno", action = "http://www.example.org/esceula/escuelaalumno")
    @WebResult(name = "alumnoResponse", targetNamespace = "http://www.example.org/escuela/", partName = "parameters")
    public AlumnoResponse escuelaAlumno(

        @WebParam(partName = "parameters", name = "alumnoRequest", targetNamespace = "http://www.example.org/escuela/")
        AlumnoRequest parameters
    );
}
